// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/watcher.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarframeMarketWatcher_Login_FullMethodName                 = "/watcher.WarframeMarketWatcher/Login"
	WarframeMarketWatcher_Logout_FullMethodName                = "/watcher.WarframeMarketWatcher/Logout"
	WarframeMarketWatcher_WatchItem_FullMethodName             = "/watcher.WarframeMarketWatcher/WatchItem"
	WarframeMarketWatcher_WatchAllItem_FullMethodName          = "/watcher.WarframeMarketWatcher/WatchAllItem"
	WarframeMarketWatcher_ListItems_FullMethodName             = "/watcher.WarframeMarketWatcher/ListItems"
	WarframeMarketWatcher_GetItemById_FullMethodName           = "/watcher.WarframeMarketWatcher/GetItemById"
	WarframeMarketWatcher_GetItemBySlug_FullMethodName         = "/watcher.WarframeMarketWatcher/GetItemBySlug"
	WarframeMarketWatcher_GetItemOrders_FullMethodName         = "/watcher.WarframeMarketWatcher/GetItemOrders"
	WarframeMarketWatcher_GetTopItemOrders_FullMethodName      = "/watcher.WarframeMarketWatcher/GetTopItemOrders"
	WarframeMarketWatcher_GetMyOrders_FullMethodName           = "/watcher.WarframeMarketWatcher/GetMyOrders"
	WarframeMarketWatcher_CreateOrder_FullMethodName           = "/watcher.WarframeMarketWatcher/CreateOrder"
	WarframeMarketWatcher_UpdateOrder_FullMethodName           = "/watcher.WarframeMarketWatcher/UpdateOrder"
	WarframeMarketWatcher_DeleteOrder_FullMethodName           = "/watcher.WarframeMarketWatcher/DeleteOrder"
	WarframeMarketWatcher_GetRecentTransactions_FullMethodName = "/watcher.WarframeMarketWatcher/GetRecentTransactions"
	WarframeMarketWatcher_GetOrderDetail_FullMethodName        = "/watcher.WarframeMarketWatcher/GetOrderDetail"
)

// WarframeMarketWatcherClient is the client API for WarframeMarketWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WarframeMarketWatcher provides methods to watch for market updates.
type WarframeMarketWatcherClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error)
	// WatchItem allows a client to subscribe to market updates for a specific item.
	WatchItem(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketUpdate], error)
	WatchAllItem(ctx context.Context, in *AllItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AllMarketUpdate], error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ItemShortList, error)
	GetItemById(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	GetItemBySlug(ctx context.Context, in *GetItemBySlugRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	GetItemOrders(ctx context.Context, in *ItemOrdersRequest, opts ...grpc.CallOption) (*OrderList, error)
	GetTopItemOrders(ctx context.Context, in *TopItemOrdersRequest, opts ...grpc.CallOption) (*TopOrdersResponse, error)
	GetMyOrders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrderList, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	DeleteOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*ActionResponse, error)
	GetRecentTransactions(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*TransactionList, error)
	GetOrderDetail(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*GetOrderDetailResponse, error)
}

type warframeMarketWatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewWarframeMarketWatcherClient(cc grpc.ClientConnInterface) WarframeMarketWatcherClient {
	return &warframeMarketWatcherClient{cc}
}

func (c *warframeMarketWatcherClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) Logout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) WatchItem(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WarframeMarketWatcher_ServiceDesc.Streams[0], WarframeMarketWatcher_WatchItem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ItemRequest, MarketUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WarframeMarketWatcher_WatchItemClient = grpc.ServerStreamingClient[MarketUpdate]

func (c *warframeMarketWatcherClient) WatchAllItem(ctx context.Context, in *AllItemRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AllMarketUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WarframeMarketWatcher_ServiceDesc.Streams[1], WarframeMarketWatcher_WatchAllItem_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AllItemRequest, AllMarketUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WarframeMarketWatcher_WatchAllItemClient = grpc.ServerStreamingClient[AllMarketUpdate]

func (c *warframeMarketWatcherClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ItemShortList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemShortList)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetItemById(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetItemById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetItemBySlug(ctx context.Context, in *GetItemBySlugRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetItemBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetItemOrders(ctx context.Context, in *ItemOrdersRequest, opts ...grpc.CallOption) (*OrderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderList)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetItemOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetTopItemOrders(ctx context.Context, in *TopItemOrdersRequest, opts ...grpc.CallOption) (*TopOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopOrdersResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetTopItemOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetMyOrders(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderList)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetMyOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) DeleteOrder(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_DeleteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetRecentTransactions(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*TransactionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionList)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetRecentTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warframeMarketWatcherClient) GetOrderDetail(ctx context.Context, in *OrderId, opts ...grpc.CallOption) (*GetOrderDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderDetailResponse)
	err := c.cc.Invoke(ctx, WarframeMarketWatcher_GetOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarframeMarketWatcherServer is the server API for WarframeMarketWatcher service.
// All implementations must embed UnimplementedWarframeMarketWatcherServer
// for forward compatibility.
//
// WarframeMarketWatcher provides methods to watch for market updates.
type WarframeMarketWatcherServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *Empty) (*ActionResponse, error)
	// WatchItem allows a client to subscribe to market updates for a specific item.
	WatchItem(*ItemRequest, grpc.ServerStreamingServer[MarketUpdate]) error
	WatchAllItem(*AllItemRequest, grpc.ServerStreamingServer[AllMarketUpdate]) error
	ListItems(context.Context, *ListItemsRequest) (*ItemShortList, error)
	GetItemById(context.Context, *GetItemRequest) (*GetItemResponse, error)
	GetItemBySlug(context.Context, *GetItemBySlugRequest) (*GetItemResponse, error)
	GetItemOrders(context.Context, *ItemOrdersRequest) (*OrderList, error)
	GetTopItemOrders(context.Context, *TopItemOrdersRequest) (*TopOrdersResponse, error)
	GetMyOrders(context.Context, *Empty) (*OrderList, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*ActionResponse, error)
	UpdateOrder(context.Context, *UpdateOrderRequest) (*ActionResponse, error)
	DeleteOrder(context.Context, *OrderId) (*ActionResponse, error)
	GetRecentTransactions(context.Context, *ItemRequest) (*TransactionList, error)
	GetOrderDetail(context.Context, *OrderId) (*GetOrderDetailResponse, error)
	mustEmbedUnimplementedWarframeMarketWatcherServer()
}

// UnimplementedWarframeMarketWatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarframeMarketWatcherServer struct{}

func (UnimplementedWarframeMarketWatcherServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) Logout(context.Context, *Empty) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) WatchItem(*ItemRequest, grpc.ServerStreamingServer[MarketUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchItem not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) WatchAllItem(*AllItemRequest, grpc.ServerStreamingServer[AllMarketUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchAllItem not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) ListItems(context.Context, *ListItemsRequest) (*ItemShortList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetItemById(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItemById not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetItemBySlug(context.Context, *GetItemBySlugRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItemBySlug not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetItemOrders(context.Context, *ItemOrdersRequest) (*OrderList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItemOrders not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetTopItemOrders(context.Context, *TopItemOrdersRequest) (*TopOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopItemOrders not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetMyOrders(context.Context, *Empty) (*OrderList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyOrders not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) CreateOrder(context.Context, *CreateOrderRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) DeleteOrder(context.Context, *OrderId) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrder not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetRecentTransactions(context.Context, *ItemRequest) (*TransactionList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentTransactions not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) GetOrderDetail(context.Context, *OrderId) (*GetOrderDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderDetail not implemented")
}
func (UnimplementedWarframeMarketWatcherServer) mustEmbedUnimplementedWarframeMarketWatcherServer() {}
func (UnimplementedWarframeMarketWatcherServer) testEmbeddedByValue()                               {}

// UnsafeWarframeMarketWatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarframeMarketWatcherServer will
// result in compilation errors.
type UnsafeWarframeMarketWatcherServer interface {
	mustEmbedUnimplementedWarframeMarketWatcherServer()
}

func RegisterWarframeMarketWatcherServer(s grpc.ServiceRegistrar, srv WarframeMarketWatcherServer) {
	// If the following call panics, it indicates UnimplementedWarframeMarketWatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarframeMarketWatcher_ServiceDesc, srv)
}

func _WarframeMarketWatcher_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).Logout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_WatchItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WarframeMarketWatcherServer).WatchItem(m, &grpc.GenericServerStream[ItemRequest, MarketUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WarframeMarketWatcher_WatchItemServer = grpc.ServerStreamingServer[MarketUpdate]

func _WarframeMarketWatcher_WatchAllItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WarframeMarketWatcherServer).WatchAllItem(m, &grpc.GenericServerStream[AllItemRequest, AllMarketUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WarframeMarketWatcher_WatchAllItemServer = grpc.ServerStreamingServer[AllMarketUpdate]

func _WarframeMarketWatcher_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetItemById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetItemById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetItemById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetItemById(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetItemBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetItemBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetItemBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetItemBySlug(ctx, req.(*GetItemBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetItemOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetItemOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetItemOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetItemOrders(ctx, req.(*ItemOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetTopItemOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopItemOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetTopItemOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetTopItemOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetTopItemOrders(ctx, req.(*TopItemOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetMyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetMyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetMyOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetMyOrders(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_DeleteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).DeleteOrder(ctx, req.(*OrderId))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetRecentTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetRecentTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetRecentTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetRecentTransactions(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarframeMarketWatcher_GetOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarframeMarketWatcherServer).GetOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarframeMarketWatcher_GetOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarframeMarketWatcherServer).GetOrderDetail(ctx, req.(*OrderId))
	}
	return interceptor(ctx, in, info, handler)
}

// WarframeMarketWatcher_ServiceDesc is the grpc.ServiceDesc for WarframeMarketWatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarframeMarketWatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watcher.WarframeMarketWatcher",
	HandlerType: (*WarframeMarketWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _WarframeMarketWatcher_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _WarframeMarketWatcher_Logout_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _WarframeMarketWatcher_ListItems_Handler,
		},
		{
			MethodName: "GetItemById",
			Handler:    _WarframeMarketWatcher_GetItemById_Handler,
		},
		{
			MethodName: "GetItemBySlug",
			Handler:    _WarframeMarketWatcher_GetItemBySlug_Handler,
		},
		{
			MethodName: "GetItemOrders",
			Handler:    _WarframeMarketWatcher_GetItemOrders_Handler,
		},
		{
			MethodName: "GetTopItemOrders",
			Handler:    _WarframeMarketWatcher_GetTopItemOrders_Handler,
		},
		{
			MethodName: "GetMyOrders",
			Handler:    _WarframeMarketWatcher_GetMyOrders_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _WarframeMarketWatcher_CreateOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _WarframeMarketWatcher_UpdateOrder_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _WarframeMarketWatcher_DeleteOrder_Handler,
		},
		{
			MethodName: "GetRecentTransactions",
			Handler:    _WarframeMarketWatcher_GetRecentTransactions_Handler,
		},
		{
			MethodName: "GetOrderDetail",
			Handler:    _WarframeMarketWatcher_GetOrderDetail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchItem",
			Handler:       _WarframeMarketWatcher_WatchItem_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchAllItem",
			Handler:       _WarframeMarketWatcher_WatchAllItem_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/watcher.proto",
}
