// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/watcher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_watcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{0}
}

// AllItemRequest represents the request to watch all items
type AllItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllItemRequest) Reset() {
	*x = AllItemRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllItemRequest) ProtoMessage() {}

func (x *AllItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllItemRequest.ProtoReflect.Descriptor instead.
func (*AllItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{1}
}

// ItemRequest represents the request to watch a specific item.
type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{2}
}

func (x *ItemRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Request message for getting an item
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetItemRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type GetItemBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemSlug      string                 `protobuf:"bytes,1,opt,name=item_slug,json=itemSlug,proto3" json:"item_slug,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemBySlugRequest) Reset() {
	*x = GetItemBySlugRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemBySlugRequest) ProtoMessage() {}

func (x *GetItemBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetItemBySlugRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemBySlugRequest) GetItemSlug() string {
	if x != nil {
		return x.ItemSlug
	}
	return ""
}

func (x *GetItemBySlugRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Top-level response envelope
type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Data          *ItemDetail            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_api_proto_watcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetItemResponse) GetData() *ItemDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetItemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	GameRef       string                 `protobuf:"bytes,3,opt,name=game_ref,json=gameRef,proto3" json:"game_ref,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Subtypes      []string               `protobuf:"bytes,5,rep,name=subtypes,proto3" json:"subtypes,omitempty"`
	Vaulted       bool                   `protobuf:"varint,6,opt,name=vaulted,proto3" json:"vaulted,omitempty"`
	TradingTax    int32                  `protobuf:"varint,7,opt,name=trading_tax,json=tradingTax,proto3" json:"trading_tax,omitempty"`
	Tradable      bool                   `protobuf:"varint,8,opt,name=tradable,proto3" json:"tradable,omitempty"`
	I18N          *ItemI18N              `protobuf:"bytes,9,opt,name=i18n,proto3" json:"i18n,omitempty"`
	MaxRank       int32                  `protobuf:"varint,10,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	Ducats        int32                  `protobuf:"varint,11,opt,name=ducats,proto3" json:"ducats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDetail) Reset() {
	*x = ItemDetail{}
	mi := &file_api_proto_watcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDetail) ProtoMessage() {}

func (x *ItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDetail.ProtoReflect.Descriptor instead.
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{7}
}

func (x *ItemDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ItemDetail) GetGameRef() string {
	if x != nil {
		return x.GameRef
	}
	return ""
}

func (x *ItemDetail) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemDetail) GetSubtypes() []string {
	if x != nil {
		return x.Subtypes
	}
	return nil
}

func (x *ItemDetail) GetVaulted() bool {
	if x != nil {
		return x.Vaulted
	}
	return false
}

func (x *ItemDetail) GetTradingTax() int32 {
	if x != nil {
		return x.TradingTax
	}
	return 0
}

func (x *ItemDetail) GetTradable() bool {
	if x != nil {
		return x.Tradable
	}
	return false
}

func (x *ItemDetail) GetI18N() *ItemI18N {
	if x != nil {
		return x.I18N
	}
	return nil
}

func (x *ItemDetail) GetMaxRank() int32 {
	if x != nil {
		return x.MaxRank
	}
	return 0
}

func (x *ItemDetail) GetDucats() int32 {
	if x != nil {
		return x.Ducats
	}
	return 0
}

type ItemI18N struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	En            *ItemLanguageDetail    `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemI18N) Reset() {
	*x = ItemI18N{}
	mi := &file_api_proto_watcher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemI18N) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemI18N) ProtoMessage() {}

func (x *ItemI18N) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemI18N.ProtoReflect.Descriptor instead.
func (*ItemI18N) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{8}
}

func (x *ItemI18N) GetEn() *ItemLanguageDetail {
	if x != nil {
		return x.En
	}
	return nil
}

type ItemLanguageDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Thumb         string                 `protobuf:"bytes,4,opt,name=thumb,proto3" json:"thumb,omitempty"`
	SubIcon       string                 `protobuf:"bytes,5,opt,name=sub_icon,json=subIcon,proto3" json:"sub_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLanguageDetail) Reset() {
	*x = ItemLanguageDetail{}
	mi := &file_api_proto_watcher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLanguageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLanguageDetail) ProtoMessage() {}

func (x *ItemLanguageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLanguageDetail.ProtoReflect.Descriptor instead.
func (*ItemLanguageDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{9}
}

func (x *ItemLanguageDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemLanguageDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemLanguageDetail) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ItemLanguageDetail) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

func (x *ItemLanguageDetail) GetSubIcon() string {
	if x != nil {
		return x.SubIcon
	}
	return ""
}

type ItemShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	GameRef       string                 `protobuf:"bytes,3,opt,name=game_ref,json=gameRef,proto3" json:"game_ref,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Subtypes      []string               `protobuf:"bytes,5,rep,name=subtypes,proto3" json:"subtypes,omitempty"`
	Vaulted       bool                   `protobuf:"varint,6,opt,name=vaulted,proto3" json:"vaulted,omitempty"`
	MaxRank       int32                  `protobuf:"varint,7,opt,name=max_rank,json=maxRank,proto3" json:"max_rank,omitempty"`
	Ducats        int32                  `protobuf:"varint,8,opt,name=ducats,proto3" json:"ducats,omitempty"`
	I18N          *ItemI18N              `protobuf:"bytes,9,opt,name=i18n,proto3" json:"i18n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShort) Reset() {
	*x = ItemShort{}
	mi := &file_api_proto_watcher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShort) ProtoMessage() {}

func (x *ItemShort) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShort.ProtoReflect.Descriptor instead.
func (*ItemShort) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{10}
}

func (x *ItemShort) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemShort) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ItemShort) GetGameRef() string {
	if x != nil {
		return x.GameRef
	}
	return ""
}

func (x *ItemShort) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ItemShort) GetSubtypes() []string {
	if x != nil {
		return x.Subtypes
	}
	return nil
}

func (x *ItemShort) GetVaulted() bool {
	if x != nil {
		return x.Vaulted
	}
	return false
}

func (x *ItemShort) GetMaxRank() int32 {
	if x != nil {
		return x.MaxRank
	}
	return 0
}

func (x *ItemShort) GetDucats() int32 {
	if x != nil {
		return x.Ducats
	}
	return 0
}

func (x *ItemShort) GetI18N() *ItemI18N {
	if x != nil {
		return x.I18N
	}
	return nil
}

type ItemShortList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Items         []*ItemShort           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemShortList) Reset() {
	*x = ItemShortList{}
	mi := &file_api_proto_watcher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemShortList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemShortList) ProtoMessage() {}

func (x *ItemShortList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemShortList.ProtoReflect.Descriptor instead.
func (*ItemShortList) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{11}
}

func (x *ItemShortList) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ItemShortList) GetItems() []*ItemShort {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemShortList) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ItemOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemSlug      string                 `protobuf:"bytes,1,opt,name=item_slug,json=itemSlug,proto3" json:"item_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemOrdersRequest) Reset() {
	*x = ItemOrdersRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemOrdersRequest) ProtoMessage() {}

func (x *ItemOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemOrdersRequest.ProtoReflect.Descriptor instead.
func (*ItemOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{12}
}

func (x *ItemOrdersRequest) GetItemSlug() string {
	if x != nil {
		return x.ItemSlug
	}
	return ""
}

type TopItemOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemSlug      string                 `protobuf:"bytes,1,opt,name=item_slug,json=itemSlug,proto3" json:"item_slug,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopItemOrdersRequest) Reset() {
	*x = TopItemOrdersRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopItemOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopItemOrdersRequest) ProtoMessage() {}

func (x *TopItemOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopItemOrdersRequest.ProtoReflect.Descriptor instead.
func (*TopItemOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{13}
}

func (x *TopItemOrdersRequest) GetItemSlug() string {
	if x != nil {
		return x.ItemSlug
	}
	return ""
}

func (x *TopItemOrdersRequest) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// MarketUpdate represents an event matching the item being watched.
type MarketUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	OrderType     string                 `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // e.g., "sell" or "buy"
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UserName      string                 `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketUpdate) Reset() {
	*x = MarketUpdate{}
	mi := &file_api_proto_watcher_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketUpdate) ProtoMessage() {}

func (x *MarketUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketUpdate.ProtoReflect.Descriptor instead.
func (*MarketUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{14}
}

func (x *MarketUpdate) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *MarketUpdate) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *MarketUpdate) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketUpdate) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MarketUpdate) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type AllMarketUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketUpdates []*MarketUpdate        `protobuf:"bytes,1,rep,name=market_updates,json=marketUpdates,proto3" json:"market_updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllMarketUpdate) Reset() {
	*x = AllMarketUpdate{}
	mi := &file_api_proto_watcher_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllMarketUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMarketUpdate) ProtoMessage() {}

func (x *AllMarketUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMarketUpdate.ProtoReflect.Descriptor instead.
func (*AllMarketUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{15}
}

func (x *AllMarketUpdate) GetMarketUpdates() []*MarketUpdate {
	if x != nil {
		return x.MarketUpdates
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderType     string                 `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // "sell" or "buy"
	ItemSlug      string                 `protobuf:"bytes,6,opt,name=item_slug,json=itemSlug,proto3" json:"item_slug,omitempty"`
	Subtype       string                 `protobuf:"bytes,7,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Visible       bool                   `protobuf:"varint,8,opt,name=visible,proto3" json:"visible,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	User          *User                  `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_watcher_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{16}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Order) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Order) GetItemSlug() string {
	if x != nil {
		return x.ItemSlug
	}
	return ""
}

func (x *Order) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *Order) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Order) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type OrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_api_proto_watcher_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{17}
}

func (x *OrderList) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OrderList) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrderList) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TopOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Sell          []*Order               `protobuf:"bytes,2,rep,name=sell,proto3" json:"sell,omitempty"`
	Buy           []*Order               `protobuf:"bytes,3,rep,name=buy,proto3" json:"buy,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopOrdersResponse) Reset() {
	*x = TopOrdersResponse{}
	mi := &file_api_proto_watcher_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopOrdersResponse) ProtoMessage() {}

func (x *TopOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopOrdersResponse.ProtoReflect.Descriptor instead.
func (*TopOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{18}
}

func (x *TopOrdersResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *TopOrdersResponse) GetSell() []*Order {
	if x != nil {
		return x.Sell
	}
	return nil
}

func (x *TopOrdersResponse) GetBuy() []*Order {
	if x != nil {
		return x.Buy
	}
	return nil
}

func (x *TopOrdersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IngameName    string                 `protobuf:"bytes,2,opt,name=ingame_name,json=ingameName,proto3" json:"ingame_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Reputation    int32                  `protobuf:"varint,5,opt,name=reputation,proto3" json:"reputation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_watcher_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetIngameName() string {
	if x != nil {
		return x.IngameName
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *User) GetReputation() int32 {
	if x != nil {
		return x.Reputation
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Platinum      int32                  `protobuf:"varint,3,opt,name=platinum,proto3" json:"platinum,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Visible       bool                   `protobuf:"varint,5,opt,name=visible,proto3" json:"visible,omitempty"`
	Subtype       string                 `protobuf:"bytes,6,opt,name=subtype,proto3" json:"subtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{20}
}

func (x *CreateOrderRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *CreateOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOrderRequest) GetPlatinum() int32 {
	if x != nil {
		return x.Platinum
	}
	return 0
}

func (x *CreateOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *CreateOrderRequest) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Platinum      int32                  `protobuf:"varint,2,opt,name=platinum,proto3" json:"platinum,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Visible       bool                   `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_api_proto_watcher_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderRequest) GetPlatinum() int32 {
	if x != nil {
		return x.Platinum
	}
	return 0
}

func (x *UpdateOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateOrderRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_api_proto_watcher_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{22}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Transaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemName         string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Price            int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity         int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderType        string                 `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // "sell" or "buy"
	CounterpartyName string                 `protobuf:"bytes,6,opt,name=counterparty_name,json=counterpartyName,proto3" json:"counterparty_name,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_watcher_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{23}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Transaction) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Transaction) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Transaction) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Transaction) GetCounterpartyName() string {
	if x != nil {
		return x.CounterpartyName
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_api_proto_watcher_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{24}
}

func (x *TransactionList) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type OrderId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderId) Reset() {
	*x = OrderId{}
	mi := &file_api_proto_watcher_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderId) ProtoMessage() {}

func (x *OrderId) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderId.ProtoReflect.Descriptor instead.
func (*OrderId) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{25}
}

func (x *OrderId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "sell" or "buy"
	Platinum      int32                  `protobuf:"varint,3,opt,name=platinum,proto3" json:"platinum,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PerTrade      int32                  `protobuf:"varint,5,opt,name=per_trade,json=perTrade,proto3" json:"per_trade,omitempty"`
	Subtype       string                 `protobuf:"bytes,6,opt,name=subtype,proto3" json:"subtype,omitempty"` // e.g., "intact"
	Visible       bool                   `protobuf:"varint,7,opt,name=visible,proto3" json:"visible,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ItemId        string                 `protobuf:"bytes,10,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemSlug      string                 `protobuf:"bytes,11,opt,name=item_slug,json=itemSlug,proto3" json:"item_slug,omitempty"`
	User          *User                  `protobuf:"bytes,12,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	mi := &file_api_proto_watcher_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{26}
}

func (x *OrderDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderDetail) GetPlatinum() int32 {
	if x != nil {
		return x.Platinum
	}
	return 0
}

func (x *OrderDetail) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderDetail) GetPerTrade() int32 {
	if x != nil {
		return x.PerTrade
	}
	return 0
}

func (x *OrderDetail) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *OrderDetail) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *OrderDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderDetail) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderDetail) GetItemSlug() string {
	if x != nil {
		return x.ItemSlug
	}
	return ""
}

func (x *OrderDetail) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetOrderDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Data          *OrderDetail           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // empty string when no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailResponse) Reset() {
	*x = GetOrderDetailResponse{}
	mi := &file_api_proto_watcher_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResponse) ProtoMessage() {}

func (x *GetOrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_watcher_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_watcher_proto_rawDescGZIP(), []int{27}
}

func (x *GetOrderDetailResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetOrderDetailResponse) GetData() *OrderDetail {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetOrderDetailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_watcher_proto protoreflect.FileDescriptor

const file_api_proto_watcher_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/watcher.proto\x12\awatcher\"\a\n" +
	"\x05Empty\"\x10\n" +
	"\x0eAllItemRequest\"*\n" +
	"\vItemRequest\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\".\n" +
	"\x10ListItemsRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\"E\n" +
	"\x0eGetItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"O\n" +
	"\x14GetItemBySlugRequest\x12\x1b\n" +
	"\titem_slug\x18\x01 \x01(\tR\bitemSlug\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"q\n" +
	"\x0fGetItemResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.watcher.ItemDetailR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xac\x02\n" +
	"\n" +
	"ItemDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x19\n" +
	"\bgame_ref\x18\x03 \x01(\tR\agameRef\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bsubtypes\x18\x05 \x03(\tR\bsubtypes\x12\x18\n" +
	"\avaulted\x18\x06 \x01(\bR\avaulted\x12\x1f\n" +
	"\vtrading_tax\x18\a \x01(\x05R\n" +
	"tradingTax\x12\x1a\n" +
	"\btradable\x18\b \x01(\bR\btradable\x12%\n" +
	"\x04i18n\x18\t \x01(\v2\x11.watcher.ItemI18NR\x04i18n\x12\x19\n" +
	"\bmax_rank\x18\n" +
	" \x01(\x05R\amaxRank\x12\x16\n" +
	"\x06ducats\x18\v \x01(\x05R\x06ducats\"7\n" +
	"\bItemI18N\x12+\n" +
	"\x02en\x18\x01 \x01(\v2\x1b.watcher.ItemLanguageDetailR\x02en\"\x8f\x01\n" +
	"\x12ItemLanguageDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05thumb\x18\x04 \x01(\tR\x05thumb\x12\x19\n" +
	"\bsub_icon\x18\x05 \x01(\tR\asubIcon\"\xee\x01\n" +
	"\tItemShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x19\n" +
	"\bgame_ref\x18\x03 \x01(\tR\agameRef\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1a\n" +
	"\bsubtypes\x18\x05 \x03(\tR\bsubtypes\x12\x18\n" +
	"\avaulted\x18\x06 \x01(\bR\avaulted\x12\x19\n" +
	"\bmax_rank\x18\a \x01(\x05R\amaxRank\x12\x16\n" +
	"\x06ducats\x18\b \x01(\x05R\x06ducats\x12%\n" +
	"\x04i18n\x18\t \x01(\v2\x11.watcher.ItemI18NR\x04i18n\"p\n" +
	"\rItemShortList\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.watcher.ItemShortR\x05items\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"0\n" +
	"\x11ItemOrdersRequest\x12\x1b\n" +
	"\titem_slug\x18\x01 \x01(\tR\bitemSlug\"G\n" +
	"\x14TopItemOrdersRequest\x12\x1b\n" +
	"\titem_slug\x18\x01 \x01(\tR\bitemSlug\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\"\x99\x01\n" +
	"\fMarketUpdate\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"order_type\x18\x02 \x01(\tR\torderType\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1b\n" +
	"\tuser_name\x18\x05 \x01(\tR\buserName\"O\n" +
	"\x0fAllMarketUpdate\x12<\n" +
	"\x0emarket_updates\x18\x01 \x03(\v2\x15.watcher.MarketUpdateR\rmarketUpdates\"\xb3\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tR\torderType\x12\x1b\n" +
	"\titem_slug\x18\x06 \x01(\tR\bitemSlug\x12\x18\n" +
	"\asubtype\x18\a \x01(\tR\asubtype\x12\x18\n" +
	"\avisible\x18\b \x01(\bR\avisible\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12!\n" +
	"\x04user\x18\v \x01(\v2\r.watcher.UserR\x04user\"j\n" +
	"\tOrderList\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12&\n" +
	"\x06orders\x18\x02 \x03(\v2\x0e.watcher.OrderR\x06orders\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x90\x01\n" +
	"\x11TopOrdersResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\"\n" +
	"\x04sell\x18\x02 \x03(\v2\x0e.watcher.OrderR\x04sell\x12 \n" +
	"\x03buy\x18\x03 \x03(\v2\x0e.watcher.OrderR\x03buy\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8b\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vingame_name\x18\x02 \x01(\tR\n" +
	"ingameName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"reputation\x18\x05 \x01(\x05R\n" +
	"reputation\"\xad\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bplatinum\x18\x03 \x01(\x05R\bplatinum\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x18\n" +
	"\avisible\x18\x05 \x01(\bR\avisible\x12\x18\n" +
	"\asubtype\x18\x06 \x01(\tR\asubtype\"v\n" +
	"\x12UpdateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bplatinum\x18\x02 \x01(\x05R\bplatinum\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x18\n" +
	"\avisible\x18\x04 \x01(\bR\avisible\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd7\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tR\torderType\x12+\n" +
	"\x11counterparty_name\x18\x06 \x01(\tR\x10counterpartyName\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"K\n" +
	"\x0fTransactionList\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.watcher.TransactionR\ftransactions\"\x19\n" +
	"\aOrderId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd1\x02\n" +
	"\vOrderDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bplatinum\x18\x03 \x01(\x05R\bplatinum\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1b\n" +
	"\tper_trade\x18\x05 \x01(\x05R\bperTrade\x12\x18\n" +
	"\asubtype\x18\x06 \x01(\tR\asubtype\x12\x18\n" +
	"\avisible\x18\a \x01(\bR\avisible\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x17\n" +
	"\aitem_id\x18\n" +
	" \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_slug\x18\v \x01(\tR\bitemSlug\x12!\n" +
	"\x04user\x18\f \x01(\v2\r.watcher.UserR\x04user\"y\n" +
	"\x16GetOrderDetailResponse\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.watcher.OrderDetailR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xfd\x06\n" +
	"\x15WarframeMarketWatcher\x12<\n" +
	"\tWatchItem\x12\x14.watcher.ItemRequest\x1a\x15.watcher.MarketUpdate\"\x000\x01\x12E\n" +
	"\fWatchAllItem\x12\x17.watcher.AllItemRequest\x1a\x18.watcher.AllMarketUpdate\"\x000\x01\x12>\n" +
	"\tListItems\x12\x19.watcher.ListItemsRequest\x1a\x16.watcher.ItemShortList\x12@\n" +
	"\vGetItemById\x12\x17.watcher.GetItemRequest\x1a\x18.watcher.GetItemResponse\x12H\n" +
	"\rGetItemBySlug\x12\x1d.watcher.GetItemBySlugRequest\x1a\x18.watcher.GetItemResponse\x12?\n" +
	"\rGetItemOrders\x12\x1a.watcher.ItemOrdersRequest\x1a\x12.watcher.OrderList\x12M\n" +
	"\x10GetTopItemOrders\x12\x1d.watcher.TopItemOrdersRequest\x1a\x1a.watcher.TopOrdersResponse\x121\n" +
	"\vGetMyOrders\x12\x0e.watcher.Empty\x1a\x12.watcher.OrderList\x12C\n" +
	"\vCreateOrder\x12\x1b.watcher.CreateOrderRequest\x1a\x17.watcher.ActionResponse\x12C\n" +
	"\vUpdateOrder\x12\x1b.watcher.UpdateOrderRequest\x1a\x17.watcher.ActionResponse\x128\n" +
	"\vDeleteOrder\x12\x10.watcher.OrderId\x1a\x17.watcher.ActionResponse\x12G\n" +
	"\x15GetRecentTransactions\x12\x14.watcher.ItemRequest\x1a\x18.watcher.TransactionList\x12C\n" +
	"\x0eGetOrderDetail\x12\x10.watcher.OrderId\x1a\x1f.watcher.GetOrderDetailResponseB0Z.github.com/azzykesuma/warframeMarket/api/protob\x06proto3"

var (
	file_api_proto_watcher_proto_rawDescOnce sync.Once
	file_api_proto_watcher_proto_rawDescData []byte
)

func file_api_proto_watcher_proto_rawDescGZIP() []byte {
	file_api_proto_watcher_proto_rawDescOnce.Do(func() {
		file_api_proto_watcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_watcher_proto_rawDesc), len(file_api_proto_watcher_proto_rawDesc)))
	})
	return file_api_proto_watcher_proto_rawDescData
}

var file_api_proto_watcher_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_watcher_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: watcher.Empty
	(*AllItemRequest)(nil),         // 1: watcher.AllItemRequest
	(*ItemRequest)(nil),            // 2: watcher.ItemRequest
	(*ListItemsRequest)(nil),       // 3: watcher.ListItemsRequest
	(*GetItemRequest)(nil),         // 4: watcher.GetItemRequest
	(*GetItemBySlugRequest)(nil),   // 5: watcher.GetItemBySlugRequest
	(*GetItemResponse)(nil),        // 6: watcher.GetItemResponse
	(*ItemDetail)(nil),             // 7: watcher.ItemDetail
	(*ItemI18N)(nil),               // 8: watcher.ItemI18N
	(*ItemLanguageDetail)(nil),     // 9: watcher.ItemLanguageDetail
	(*ItemShort)(nil),              // 10: watcher.ItemShort
	(*ItemShortList)(nil),          // 11: watcher.ItemShortList
	(*ItemOrdersRequest)(nil),      // 12: watcher.ItemOrdersRequest
	(*TopItemOrdersRequest)(nil),   // 13: watcher.TopItemOrdersRequest
	(*MarketUpdate)(nil),           // 14: watcher.MarketUpdate
	(*AllMarketUpdate)(nil),        // 15: watcher.AllMarketUpdate
	(*Order)(nil),                  // 16: watcher.Order
	(*OrderList)(nil),              // 17: watcher.OrderList
	(*TopOrdersResponse)(nil),      // 18: watcher.TopOrdersResponse
	(*User)(nil),                   // 19: watcher.User
	(*CreateOrderRequest)(nil),     // 20: watcher.CreateOrderRequest
	(*UpdateOrderRequest)(nil),     // 21: watcher.UpdateOrderRequest
	(*ActionResponse)(nil),         // 22: watcher.ActionResponse
	(*Transaction)(nil),            // 23: watcher.Transaction
	(*TransactionList)(nil),        // 24: watcher.TransactionList
	(*OrderId)(nil),                // 25: watcher.OrderId
	(*OrderDetail)(nil),            // 26: watcher.OrderDetail
	(*GetOrderDetailResponse)(nil), // 27: watcher.GetOrderDetailResponse
}
var file_api_proto_watcher_proto_depIdxs = []int32{
	7,  // 0: watcher.GetItemResponse.data:type_name -> watcher.ItemDetail
	8,  // 1: watcher.ItemDetail.i18n:type_name -> watcher.ItemI18N
	9,  // 2: watcher.ItemI18N.en:type_name -> watcher.ItemLanguageDetail
	8,  // 3: watcher.ItemShort.i18n:type_name -> watcher.ItemI18N
	10, // 4: watcher.ItemShortList.items:type_name -> watcher.ItemShort
	14, // 5: watcher.AllMarketUpdate.market_updates:type_name -> watcher.MarketUpdate
	19, // 6: watcher.Order.user:type_name -> watcher.User
	16, // 7: watcher.OrderList.orders:type_name -> watcher.Order
	16, // 8: watcher.TopOrdersResponse.sell:type_name -> watcher.Order
	16, // 9: watcher.TopOrdersResponse.buy:type_name -> watcher.Order
	23, // 10: watcher.TransactionList.transactions:type_name -> watcher.Transaction
	19, // 11: watcher.OrderDetail.user:type_name -> watcher.User
	26, // 12: watcher.GetOrderDetailResponse.data:type_name -> watcher.OrderDetail
	2,  // 13: watcher.WarframeMarketWatcher.WatchItem:input_type -> watcher.ItemRequest
	1,  // 14: watcher.WarframeMarketWatcher.WatchAllItem:input_type -> watcher.AllItemRequest
	3,  // 15: watcher.WarframeMarketWatcher.ListItems:input_type -> watcher.ListItemsRequest
	4,  // 16: watcher.WarframeMarketWatcher.GetItemById:input_type -> watcher.GetItemRequest
	5,  // 17: watcher.WarframeMarketWatcher.GetItemBySlug:input_type -> watcher.GetItemBySlugRequest
	12, // 18: watcher.WarframeMarketWatcher.GetItemOrders:input_type -> watcher.ItemOrdersRequest
	13, // 19: watcher.WarframeMarketWatcher.GetTopItemOrders:input_type -> watcher.TopItemOrdersRequest
	0,  // 20: watcher.WarframeMarketWatcher.GetMyOrders:input_type -> watcher.Empty
	20, // 21: watcher.WarframeMarketWatcher.CreateOrder:input_type -> watcher.CreateOrderRequest
	21, // 22: watcher.WarframeMarketWatcher.UpdateOrder:input_type -> watcher.UpdateOrderRequest
	25, // 23: watcher.WarframeMarketWatcher.DeleteOrder:input_type -> watcher.OrderId
	2,  // 24: watcher.WarframeMarketWatcher.GetRecentTransactions:input_type -> watcher.ItemRequest
	25, // 25: watcher.WarframeMarketWatcher.GetOrderDetail:input_type -> watcher.OrderId
	14, // 26: watcher.WarframeMarketWatcher.WatchItem:output_type -> watcher.MarketUpdate
	15, // 27: watcher.WarframeMarketWatcher.WatchAllItem:output_type -> watcher.AllMarketUpdate
	11, // 28: watcher.WarframeMarketWatcher.ListItems:output_type -> watcher.ItemShortList
	6,  // 29: watcher.WarframeMarketWatcher.GetItemById:output_type -> watcher.GetItemResponse
	6,  // 30: watcher.WarframeMarketWatcher.GetItemBySlug:output_type -> watcher.GetItemResponse
	17, // 31: watcher.WarframeMarketWatcher.GetItemOrders:output_type -> watcher.OrderList
	18, // 32: watcher.WarframeMarketWatcher.GetTopItemOrders:output_type -> watcher.TopOrdersResponse
	17, // 33: watcher.WarframeMarketWatcher.GetMyOrders:output_type -> watcher.OrderList
	22, // 34: watcher.WarframeMarketWatcher.CreateOrder:output_type -> watcher.ActionResponse
	22, // 35: watcher.WarframeMarketWatcher.UpdateOrder:output_type -> watcher.ActionResponse
	22, // 36: watcher.WarframeMarketWatcher.DeleteOrder:output_type -> watcher.ActionResponse
	24, // 37: watcher.WarframeMarketWatcher.GetRecentTransactions:output_type -> watcher.TransactionList
	27, // 38: watcher.WarframeMarketWatcher.GetOrderDetail:output_type -> watcher.GetOrderDetailResponse
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_proto_watcher_proto_init() }
func file_api_proto_watcher_proto_init() {
	if File_api_proto_watcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_watcher_proto_rawDesc), len(file_api_proto_watcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_watcher_proto_goTypes,
		DependencyIndexes: file_api_proto_watcher_proto_depIdxs,
		MessageInfos:      file_api_proto_watcher_proto_msgTypes,
	}.Build()
	File_api_proto_watcher_proto = out.File
	file_api_proto_watcher_proto_goTypes = nil
	file_api_proto_watcher_proto_depIdxs = nil
}
